import type { Metadata } from "next";
import { AestheticHeader } from "@/components/layout/header";
import GradualBlurMemo from "@/components/effects/gradual-blur";


export const metadata: Metadata = {
    title: "fysk",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <AestheticHeader />
            <div className="relative">
                {children}
            </div>
            <GradualBlurMemo
                target="page"
                position="bottom"
                height="6rem"
                strength={2}
                divCount={5}
                curve="bezier"
                exponential={true}
                opacity={1}
            />
        </>
    );
}
