import type { Metadata } from "next";
import { SUSE } from "next/font/google";
import "./globals.css";
import { FyskProvider } from "@fysk/ui";
import { ThemeProvider } from "next-themes";

const suseSans = SUSE({
  variable: "--font-suse-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${suseSans.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <FyskProvider>
            {children}
          </FyskProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
